### PR TITLE
Read VERSION file

### PR DESCRIPTION
**Pull request by bear454**

### CODE REVIEW

**Review by rjschwei — CHANGES_REQUESTED** [review]
You also need to bump the version in teh spec file or `make tar` will fail. Looks good otherwise.

**Comment by bear454** [comment]
> You also need to bump the version in teh spec file or `make tar` will fail. Looks good otherwise.

Fixed in 71225f3. `make tar` works now. Thanks.

**Review by rjschwei — COMMENTED** [review]
Would you also please update the package, thanks

**Comment by bear454** [comment]
Already did: https://build.opensuse.org/package/revisions/Cloud:Tools/python3-serviceAccessConfig

**Pull request merged**
